### ISSUE TITLE
Configurable publish phases in `builder.toml`

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2903]
## User Story

As a user of builder's builds, I need a way to declare configurable publish phases which will be performed by a builder-worker after the initial build phase, so I can consume my built artifact in various post-processed formats such as a Docker container, an AMI, etc

## Requirements

The `builder.toml` which resides next to a `plan.sh`/`plan.ps1` is the configuration that a builder-worker reads to understand additional steps. A refactored version of this may look something like this (with thanks to @tduffield)

```toml
[[publish]]
type = "docker-registry"
registry = "index.docker.io" # default
image_name = "{{pkg_origin}}/{{pkg_name}}" # default
tags = [ "{{pkg_version}}-{{pkg_release}}" ] # default
secret_key = "ENCRYPTED_VALUE" # placeholder for encrypted creds (if needed)

[[publish]]
type = "s3"
secret_key = "ENCRYPTED_VALUE"

[[publish]]
type = "artifactory"
secret_key = "ENCRYPTED_VALUE"
```

Some things to note:

* The `type` key/value represents the exporter/publisher to use for the phase
* We support an array of tables so multiple exporters of a single type can be used
* We have dropped the current configuration for publishing to the depot itself. This will become a requirement of the system
* Mustache can be used for string substitution for variables generated by the build phase such as pkg name, version, origin, and release
