### ISSUE TITLE
Leader election not being triggered

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2977]
Playing around with the postgresql cluster usecase using [this docker-compose file](https://github.com/starkandwayne/habitat-plans/blob/master/postgresql/tests/docker-compose.yml)

After starting the nodes a cluster will form but when killing the leader no new election is being triggered.

Reproduce via:
```
$ docker-compose up
```

Wait until the election has completed and figure out which node is the leader, kill that leader from another terminal via:
```
$ docker-compose stop pg1 # could be another node when you run this
```

The end of the output stream will contain:
```
pg3_1         | postgresql.cluster(SV): Starting service as user=root, group=root
pg3_1         | postgresql.cluster(O): Executing run hook
pg3_1         | postgresql.cluster(O): Writing postgresql.local.conf file based on memory settings
pg3_1         | postgresql.cluster(O): Bootstrapping replica via pg_basebackup from leader
pg2_1         | postgresql.cluster(O): Making sure hab user owns var, config and data paths
pg2_1         | postgresql.cluster(O): Starting PostgreSQL
pg2_1         | postgresql.cluster(O): 2017-08-21 09:21:23 GMT [65]: [1-1] user=,db=,client=  (0:00000)LOG:  redirecting log output to logging collector process
pg2_1         | postgresql.cluster(O): 2017-08-21 09:21:23 GMT [65]: [2-1] user=,db=,client=  (0:00000)HINT:  Future log output will appear in directory "/hab/svc/postgresql/var/pg_log".
pg3_1         | postgresql.cluster(O): Making sure hab user owns var, config and data paths
pg3_1         | postgresql.cluster(O): Starting PostgreSQL
pg3_1         | postgresql.cluster(O): 2017-08-21 09:21:23 GMT [69]: [1-1] user=,db=,client=  (0:00000)LOG:  redirecting log output to logging collector process
pg3_1         | postgresql.cluster(O): 2017-08-21 09:21:23 GMT [69]: [2-1] user=,db=,client=  (0:00000)HINT:  Future log output will appear in directory "/hab/svc/postgresql/var/pg_log".
tests_pg1_1 exited with code 137
pg3_1         | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
pg2_1         | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
standalone_1  | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
pg3_1         | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
pg2_1         | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
standalone_1  | Could not send rumor to "eaaea15527084ea8ae33fd8144b0cae1" @ "172.27.0.5:9638"; ZMQ said: Resource temporarily unavailable
```

I would expect a new election to get triggered.

**Comment by reset** [comment]
I think this is a network connectivity issue between nodes over TCP on port 9638. That's typically when we see the could not send rumor message

**Comment by bodymindarts** [comment]
This is running locally on docker for mac! No way its a connection issue.

**Comment by bodymindarts** [comment]
Just made sure and can confirm that I am able to telnet from every node to every other node on port 9638.

**Comment by bodymindarts** [comment]
docker compose file to reproduce:
```
version: '2'

services:
  standalone:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql"
  pg1:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
  pg2:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
  pg3:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
  tests:
    image: starkandwayne-postgresql-tests
    build: ./
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: postgres
    links:
    - standalone
```

**Comment by reset** [comment]
The root cause of this is likely the same as #2976. See the discussion there

**Comment by bodymindarts** [comment]
I have removed the wal-e sidecar process from PG but this issue persists, so it seems to have another root cause as https://github.com/habitat-sh/habitat/issues/2976.

**Comment by bodymindarts** [comment]
@reset here are steps to reproduce:

use this docker-compose file:
```
version: '2'

services:
  standalone:
    ports:
    - 9631:9631
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql"
    environment:
      HAB_POSTGRESQL: |

  pg1:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
  pg2:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
  pg3:
    image: starkandwayne/postgresql:edge
    command: "start starkandwayne/postgresql --group cluster --peer standalone --topology leader"
    links:
    - standalone
```
and run:
```
docker-compose up
```
Wait a littler while until the cluster has stabilized.
Then in another tab:
```
leader_container=$(curl -s localhost:9631/census | jq -r '.census_groups["postgresql.cluster"].population | to_entries | .[].value | select(.leader) | .sys.hostname')
docker stop ${leader_container}
```

This will kill the current leader, health check output from the remaining nodes should look something like:
```
pg1_1         | postgresql.cluster hook[health_check]:(HK): Master pg is unavailable at 192.168.208.5 ! Health State for follower is critical
pg3_1         | postgresql.cluster hook[health_check]:(HK): Master pg is unavailable at 192.168.208.5 ! Health State for follower is critical
```

But no new leader will be elected!
