### ISSUE TITLE
Unable to parse TOML/JSON from ENV

### ISSUE THREAD

**Issue by qhartman** [habitat-sh/habitat#4439]
I am attempting to use HAB_PACKAGENAME environment variables to override default.toml config options in my docker-packaged application, and no matter what content I put in the HAB_PACKAGENAME envvar, the hab sup reports that it cannot parse the content:
```
Unable to start finalze/active-oversight-api, hab-sup(CF)[src/manager/service/config.rs:248:20]: Unable to find valid TOML or JSON in HAB_ACTIVE_OVERSIGHT_API ENVVAR
```

I have tried working with habitat versions 0.50.3 and 0.51 with the same results. The same behavior has been observed on ECS running the latest docker-optimized Amazon Linux AMI as well as locally on a machine running Docker CE 17.12.0-ce on Ubuntu Linux 17.10

docker-compose snippet:
```
    ao-worker:
        image: "finalze/active-oversight-api"
        environment:
                - HAB_ACTIVE_OVERSIGHT_API="{'worker':'true'}"
        hostname: "ao-worker"
        links:
            - postgres
            - elasticsearch
            - redis
```

env content within the container:
```
HAB_ACTIVE_OVERSIGHT_API="{'worker':'true'}"
```

other env contents that have produced the same error:
```
HAB_ACTIVE_OVERSIGHT_API='worker="true"'
HAB_ACTIVE_OVERSIGHT_API="worker='true'"
HAB_ACTIVE_OVERSIGHT_API="worker=true"
HAB_ACTIVE_OVERSIGHT_API=""
HAB_ACTIVE_OVERSIGHT_API="{}"
HAB_ACTIVE_OVERSIGHT_API={}
```
