### ISSUE TITLE
After stopping the sup leader I don't see a new election taking place

### ISSUE THREAD

**Issue by epierotto** [habitat-sh/habitat#4759]
Hi, I'm doing some testing on how leader election will trigger hooks and reconfigure my app.

I'm using a docker compose file that runs 3 containers of my app.
- On the first start I can see the leader election happening on the logs and the app is configured and started properly
- Once the app is running I stop the leader container and I can see that there new election never happens
- Even if I start the stopped container there is no new leader election, since that my config is relying on `{{#if svc.me.leader ~}}` to configure some stuff that never happens.

I realise that this also happens running this [example of posgresql](https://github.com/habitat-sh/core-plans/tree/master/postgresql), a new leader election is never triggered.

```yml
version: '3'

services:
  pg1:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
    volumes:
      - pg1-data:/hab/svc/postgresql/data
  pg2:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
      --peer pg1
    volumes:
      - pg2-data:/hab/svc/postgresql/data
  pg3:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
      --peer pg1
    volumes:
      - pg3-data:/hab/svc/postgresql/data

volumes:
  pg1-data:
  pg2-data:
  pg3-data:
```
So the steps to reproduce are:
- Start the docker-compose example
- Stop the leader
- Restart the stopped container to re-join

Tested on both OS with same result

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] The OS (including version) where you are running any of the Habitat commands.
  - CentOS Linux release 7.3.1611 (Core) 
    - Docker version 17.12.1-ce, build 7390fc6
    - docker-compose version 1.19.0, build 9e633ef
    - hab 0.54.0/20180221022026 (My package is running this version)
  - Mac OS X 10.13.3 BuildVersion: 17D47
    - Docker version 17.12.0-ce, build c97c6d6
    - docker-compose version 1.18.0, build 8dd22a9
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>
