### ISSUE TITLE
Hab config apply is not overwriting default values

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#5056]
Greetings!

It appears that the hab config apply command is not overwriting default values for services.  Here are the full repro steps:

# Initial Setup
Create new docker-compose.yml file

**docker-compose.yml**
```
version: '3'

services:
  pg1:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
    volumes:
      - pg1-data:/hab/svc/postgresql/data
  pg2:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
      --peer pg1
    volumes:
      - pg2-data:/hab/svc/postgresql/data
  pg3:
    image: habitat/postgresql
    command: --group cluster
      --topology leader
      --peer pg1
    volumes:
      - pg3-data:/hab/svc/postgresql/data

volumes:
  pg1-data:
  pg2-data:
  pg3-data:
```

Run this command:
```bash
$ docker-compose up
```

# Investigating

## Entering a Docker container
Find the ids of the running postgresql containers
```bash
$ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                NAMES
ff583216fe5d        habitat/postgresql                                 "/init.sh --group cl…"   2 minutes ago       Up About a minute   5432/tcp, 9631/tcp   postgresql_pg1_1
4fccaa355b9a        habitat/postgresql                                 "/init.sh --group cl…"   2 minutes ago       Up About a minute   5432/tcp, 9631/tcp   postgresql_pg2_1
a15a00c91b69        habitat/postgresql                                 "/init.sh --group cl…"   2 minutes ago       Up About a minute   5432/tcp, 9631/tcp   postgresql_pg3_1
```

Enter one of the containers
```
$ docker exec -it ff583216fe5d bash
```

## Installing Curl
Install the curl package
```
(in container) $ hab pkg install core/curl
```

Now find where the curl package is installed in the container
```
(in container) $ hab pkg path core/curl
/hab/pkgs/core/curl/<version>/<timestamp>
```

The curl binary will be in that path/bin/curl

## Finding the running values

Curl the services endpoint to get the running config values (NOTE - normally you would be able to run hab sup config core/postgresql, but that command is [currently bugged](https://github.com/habitat-sh/habitat/issues/5055)
```
(in container) $ /hab/pkgs/core/curl/<version>/<timestamp>/bin/curl localhost:9631/services/
```

in the output, find the superuser key, it will look something like this

```
"superuser":{"name":"admin","password":"admin"}}
```

## Updating the config values

Now let's try to update those value.  Create a new toml file:

```
(in container) $ vi new_config.toml
```

And enter this content:

**new_config.toml**
```
[superuser]
name = 'lukeskywalker'
password = '8vA5#VRz*RpctC'
```

Now run:

```
(in container) $ hab config apply postgres.cluster $(date +%s) new_config.toml
```

## Checking the values

Run this command again:
```
(in container) $ /hab/pkgs/core/curl/<version>/<timestamp>/bin/curl localhost:9631/services/
```

And look for the superuser key - it will still be set to the default values

```
"superuser":{"name":"admin","password":"admin"}}
```
