### ISSUE TITLE
`default.toml` as a Structured Configuration Interface

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#5199]
We currently expose the file `default.toml` which allows Plan authors to specify sensible defaults for configuration values. We however perform no validation at runtime when applying a configuration to a service group or allow Plan authors to mark a configuration field as required. Not being able to mark a configuration as required will lead to a service starting and failing, or worse, automatically updating and causing an outage (related https://github.com/habitat-sh/habitat/issues/5197).

We can improve this by allowing a Plan author to describe configuration information like the following:

```toml
[http.port]
default = 80
type = "integer"

[database.password]
type = "string"

[backend.aws]
optional = true
[backend.aws.username]
type = "string"
```

Using a structured format to represent the configuration will allow us to implement things like:

* Validate configuration on application to service group
* Validate handlebars templates on Studio build
* Allowing a service to be set in the `intervene` state (described in #5197) if a configuration value is missing on upgrade

This could be accomplished by reworking `default.toml` or adding a new file to sit alongside it as a replacement, keeping `default.toml` as is for backwards compatibility reasons.
