### ISSUE TITLE
ElectionNoQuorum when applying changes gradually to a set of supervisors in Kubernetes

### ISSUE THREAD

**Issue by indradhanush** [habitat-sh/habitat#5264]
When applying updates via the `habitat-service-broker`, the supervisors get stuck in the leader election if an a change is applied and the Kubernetes pods are updated one at a time. Steps to reproduce this reliably within Kubernetes are as follows:

**Install prerequisites**
- [minikube](https://github.com/kubernetes/minikube#installation)
- [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
- [helm](https://github.com/kubernetes/helm#install)
- [svcat](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install.md#installing-the-service-catalog-cli)

**Start the cluster:**

```
minikube start \
         --kubernetes-version v1.10.0 \
         --extra-config=apiserver.Authorization.Mode=RBAC \
         --bootstrapper=localkube
```

**Set docker env:**

```
eval $(minikube docker-env)
```

**Install service catalog and habitat operator in the cluster:**

```
kubectl apply -f https://raw.githubusercontent.com/habitat-sh/habitat-operator/master/examples/rbac/minikube.yml
kubectl apply -f https://raw.githubusercontent.com/Azure/helm-charts/master/docs/prerequisities/helm-rbac-config.yaml
helm init --service-account tiller --wait
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm upgrade --install catalog svc-cat/catalog --namespace catalog  --wait
helm repo add habitat https://habitat-sh.github.io/habitat-operator/helm/charts/stable/
helm install --name my-release habitat/habitat-operator --version v0.6.1
```

**Wait for all pods to be in `Running` state**

```
watch kubectl get pods --all-namespaces
```

**Get the habitat service broker and deploy**

```
go get github.com/kinvolk/habitat-service-broker/
cd $GOPATH/github.com/kinvolk/habitat-service-broker

git checkout indradhanush/multiple-instances

eval $(minikube docker-env)

make deploy-helm
```

**Wait for the service broker to be in `Ready` State**

```
watch svcat get brokers
```

**Deploy redis instances via the service broker**

```
kubectl apply -f manifests/redis/service-instance.yaml
```

This will create three pods named `redis-0`, `redis-1` and `redis-2` respectively in the `redis-habitat` namespace.

**Wait for pods to be deployed**

```
watch svcat get instances -n redis-habitat
```

**Create Kubernetes services to access supervisor API**

```
cat <<EOF >> services.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service-sup-0
  namespace: redis-habitat
spec:
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
  type: NodePort
  ports:
  - name: http-gateway-0
    nodePort: 32000
    port: 9631
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-sup-1
  namespace: redis-habitat
spec:
  selector:
    statefulset.kubernetes.io/pod-name: redis-1
  type: NodePort
  ports:
  - name: sup-http-gateway-1
    nodePort: 32001
    port: 9631
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-sup-2
  namespace: redis-habitat
spec:
  selector:
    statefulset.kubernetes.io/pod-name: redis-2
  type: NodePort
  ports:
  - name: sup-http-gateway-2
    nodePort: 32002
    port: 9631
    protocol: TCP
EOF
```

```
kubectl apply -f services.yaml
```

This exposes ports `32000`, `32001` and `32002` for the pods `redis-0`, `redis-1` and `redis-2` respectively and remains unchanged even if pods are rescheduled. The supervisor API can be accessed via `$(minikube ip):$PORT`.

**Verify supervisor state**

[Install jq](https://stedolan.github.io/jq/download/) if you don't have it already.
The following script will print the `local_member_id`, `last_election_status` and `population` for each of the supervisors:

```
for index in 0 1 2;
  do
  services=$(curl -sS $(minikube ip):3200${index}/services)
  census=$(curl -sS $(minikube ip):3200${index}/census)

  echo -n "local_member_id:"
  echo $census | jq '.local_member_id'

  echo -n "last_election_status:"
  echo $services | jq '.[0].last_election_status'

  echo -n "population:"
  echo $census | jq '.census_groups."redis.redis".population | keys'
  echo ""
done
```

**Apply the service binding**

```
kubectl apply -f manifests/redis/binding.yaml
```

Now keep a watch on the pods via `kubectl get pods -n redis-habitat`. You would notice that the pods get terminated and updated with the latest changes one at a time. When all of them have been restarted, run the above script that prints supervisor state once again. This time the election status would be stuck at `ElectionNoQuorum` and with inconsistent `population` information. In some instances I found this to contain supervisor information of already deleted pods and in others I found supervisors that did not know of all the other running supervisors.

You can read the supervisor logs by running:

```
kubectl logs -n redis-habitat redis-0 -f
kubectl logs -n redis-habitat redis-1 -f
kubectl logs -n redis-habitat redis-2 -f
```

**Delete all the pods**

```
kubectl delete pods -n redis-habitat redis-0 redis-1 redis-2
```

And now wait for the operator to fix this by creating the pods and for the pods to be in `Running` state. Run the above script to query supervisor state, it should print the correct population information and the election status should reflect as `ElectionFinished` after about 30 seconds of the pods running.

**Reproducing this again**

If you'd like to reproduce this again without starting from scratch you can run the following to remove the deployment:

```
svcat unbind redis-habitat -n redis-habitat
kubectl delete -f manifests/redis/service-instance.yaml
```

Wait for the pods to be delted and start again from the step to deploy redis instances via the service broker.

I hope I've covered all the necessary steps to reproduce it reliably. Please let me know in case any additional information is needed.
