### ISSUE TITLE
[docker exporter] Support non-service packages

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat#5600]
Docker containers aren't just used for running services; they're frequently used to package tools (eg. the Habitat studio) and more. The docker exporter should support these use cases as well. Support should be added for:

* Packaging non-service packages with no entrypoint at all (i.e. to make base images for #5589)
* User-provided entrypoints (i.e. for one-shot processes), like @elliott-davis's https://github.com/chuckleheads/pkg-export-oci

**Comment by jtimberman** [comment]
Example use case:

I have a repository that has several scripts that are run as cron jobs to pull data out of various API services and toss that data into a database, or an S3 bucket, or other such purposes. I can export the docker container with `hab pkg export docker` and then use it in a kubernetes cronjob resource like this:

```
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingest-logs
  namespace: cron-package
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry-secret
          containers:
          - name: cron-package
            image: jtimberman/cron-package:acceptance
            command:
              - /bin/bash
            args:
              - -c
              - /bin/ingest-logs.sh
            env:
              some env stuff, etc
```
