### ISSUE TITLE
hab-sup panics when pkg_export tries to export struct

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#5854]
This is order dependent:
```toml
# default.toml
[service]
http-port=1111

[foo]
foo="foo"
bar="bar"

```

```bash
pkg_exports=(
[http-port]=service.port
[foo]=foo
)
```
does not work works

```bash
pkg_exports=(
[foo]=foo
[http-port]=service.port
)
```
does not work works
--------------------

The following works:
```toml
# default.toml
[service]
http-port=1111

[moo]
foo="foo"
bar="bar"
```

```bash
pkg_exports=(
[http-port]=service.port
[moo]=moo
)
```

```bash
pkg_exports=(
[moo]=moo
[http-port]=service.port
)
```
does not work works
