### ISSUE TITLE
Bindings fail sporadically in docker-compose

### ISSUE THREAD

**Issue by TheDarkula** [habitat-sh/habitat#5951]
I'm running Arch Linux.

When working on a docker-compose cluster, I've run into an issue where this error will pop up:

```
image-name.default(SR): The specified service group 'cockroach.default' for binding 'database' is not (yet?) present in the census data.
```

If I stop the cluster, change the group name from `default` to anything else, then restart the cluster, everything works.

I can then change the group name back to `default` and it works as it should have initially.

**Comment by HT154** [comment]
Can you post your docker-compose.yml? Without looking at it, my immediate suspicion is that the container you're peering to is coming up after the container that has the `--peer` flag, so the peering never properly occurs (and therefor the bind is never gossiped)

**Comment by TheDarkula** [comment]
Here's a snippet:
```
version: "3"
services:
  cockroachdb:
    image: core/cockroach:latest
    restart: always
    command:
      --group default
    networks:
      - webnet
  binder:
    image: origin/planName:latest
    restart: always
    command:
      --group default
      --peer cockroachdb
      --bind database:cockroach.default
    depends_on:
      - cockroachdb
```
My confusion is, why does stopping the cluster, changing the group name, and restarting the cluster fix things?
