### ISSUE TITLE
Habitat built services in docker with a mounted data volume used to work, stopped working 4-5 months ago

### ISSUE THREAD

**Issue by irvingpop** [habitat-sh/habitat#6340]
Many core plans provide Docker examples telling you to mount the `svc_data_path` as a volume, like so (simplified for brevity):

```
version: '3'
services:
  mysql1:
    image: habitat/mysql:latest
    volumes:
      - mysql1-data:/hab/svc/mysql/data

volumes:
  mysql1-data:
```

This used to work really well, but stopped working on newly built containers starting sometime after September, 2018.    On anything newer than that,  we only get permissions errors when the service tries to write to its data path.  Even hooks.

```
mysql.default(SR): Initializing
mysql.default hook[init]:(HK): mkdir: cannot create directory '/hab/svc/mysql/data/tmp': Permission denied
mysql.default(HK): Initialization failed! 'init' exited with status code 1
mysql.default(SR): Initializing
mysql.default hook[init]:(HK): mkdir: cannot create directory '/hab/svc/mysql/data/tmp': Permission denied
mysql.default(HK): Initialization failed! 'init' exited with status code 1
```

Looking back through git history, I wonder if this may be the reason:
https://github.com/habitat-sh/habitat/pull/5720 . - because if you specify a volume mount in docker or k8s, the path will have already been created but with root only permissions.
