### ISSUE TITLE
Valid toml is invalid

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#6578]
Sometimes using nested keys via dots is useful:

```yaml
# YAML
spring:
  cloud:
   kafka:
     broker: broker-1
```
According to this: https://github.com/toml-lang/toml#keys it can be written as:

```toml
# TOML
sping.cloud.kafka.broker = "broker-1"
```

However validation is failed  (by `rq` and also by `tomlcheck`). I believe they use same library.

Here is the test:
```
echo "foo.bar.baz = 125" | rq -t
```

If you have lots of nested keys dealing with sections may be nightmare:

```toml
[foo]
bar = 5
[foo.baz.banny]
x = "y"
z = "xxx"
[foo.baz.bar.fizz]
r = 6
[foo.baz.bar.fizzzz]
r = 7
```

This is either bug or we need to point to correct TOML syntax reference in documentation.
Note, that habitat parses dotted configs correctly.
