### ISSUE TITLE
No gossip exchange if Organization is defined in Director service profile

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#754]
Given the two configurations on two different nodes, when a configuration is applied to the gossip ring with `hab config apply`, a `gossip.toml` is not generated on either node.

```toml
# Node 1
[cfg.services.core.redis.live.habitat]
start = "--permanent-peer --peer ${peer_ip}:9000"

[cfg.services.core.hab-builder-api.live.habitat]
start = "--permanent-peer --bind database:redis.live,router:hab-builder-router.live --peer ${peer_ip}:9000"
```

```toml
# Node 2
[cfg.services.core.hab-builder-router.live.habitat]
start = "--permanent-peer"
```

It appears to be the last segment of the service identifier, the organization. In both of these cases the organization is set to `habitat`. Removing the organization is a workaround for now!
